/*
 * File: app/view/CarListingsViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarListings.view.CarListingsViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.carlistings',

    onGridpanelSelect: function(rowmodel, record, index, eOpts) {
        // grab a reference to the detailPanel via itemId
        // the # in front of the id indicates that we would like to grab a reference by
        var detailPanel = Ext.ComponentQuery.query('#detailPanel')[0];
        // update the detailPanel with data
        // this will trigger the tpl to become updates
        detailPanel.update(record.data);
    }

});
